### PR TITLE
Initial commit of official register entry

### PR DESCRIPTION
**Pull request by CountCulture**
Still some outstanding questions

### CODE REVIEW

**Comment by CountCulture** [comment]
Notes on LEI mapping to official_register_entry schema:

- currently no field for renewal date or last updated date. renewal date seems like it might be a common field. Should last updated date also be a field, or is that sample_date (tending towards the former)?
In fact I think if we shouldn't require sample date in general. I would like to make this optional, but not sure turbot allows it.
- not using business_registry_name or business_registry_identifier as the data is somewhat problematic. This record lists the district court (Ulm) as the business register, but we will be using #de as the business register, as the entities can move between district courts (but still stay in the same jurisdiction)
- Can't decide what type of register the GLEIS is - it's not a company register. Shadow register?


Raw record (from OpenLEIs):
{"lei":"52990008SP9ETV9I7047","registered_name":"Kreissparkasse Ostalb","legal_form":"Anstalt öffentlichen Rechts","registered_address_1":"Bahnhofstraße 4","registered_address_2":null,"registered_address_3":null,"registered_address_4":null,"registered_city":"Aalen","registered_region":null,"registered_postal_code":"73430","registered_country_code":"DE","headquarter_address_1":"Bahnhofstraße 4","headquarter_address_2":null,"headquarter_address_3":null,"headquarter_address_4":null,"headquarter_city":"Aalen","headquarter_region":null,"headquarter_postal_code":"73430","headquarter_country_code":"DE","business_registry_name":"Ulm","business_registry_identifier":"HRA 500980","lou":"5299000J2N45DDNE4Y28","entity_status_code":"ACTIVE","entity_website_address":"https://www.ksk-ostalb.de/","entity_termination_date":null,"lei_assignment_date":"2013-07-25 08:40:28 UTC","lei_record_last_update":"2014-07-10 08:14:29 UTC","lei_expired_date":null,"lei_next_renewal_date":"2015-07-25 08:40:28 UTC","lei_next_certification_date":null,"lei_expired_reason_code":null,"lei_certification_status":null,"lei_status_code":"ISSUED","created_at":"2013-11-21 07:46:49 UTC","updated_at":"2015-04-26 22:07:32 UTC","retrieved_at":"2015-04-26 01:30:06 UTC","other_names":"[{\"name\":\"Kreissparkasse Ostalb\",\"language\":null,\"type\":\"AUTO_ASCII_TRANSLITERATED_LEGAL\"}]","redirected_lei":null,"redirected_lei_reason":null,"redirected_lei_effective_date":null,"meta_entity_status":"ACTIVE","meta_lei_registration_status":"ISSUED","inferred_jurisdiction_name":"Germany","source_url":"http://www.c-lei.org/","sample_date":"2015-04-26 01:30:06 UTC"}

**Comment by CountCulture** [comment]
Notes re nonprofits
- Feel it should possibly be a subclass of Official Register Entry (rather than just an instance of it)
- needs charity flag (not all nonprofits are charities)

title,charity_number,company_number,activities,contact_name,address,website,telephone,date_registered,date_removed,accounts_date,spending,income,openlylocal_url,created_at,updated_at
ASSOCIATION FOR INDUSTRIAL ARCHAEOLOGY,277511,1234,"THE AIA IS THE NATIONAL ORGANISATION FOR PEOPLE WHO SHARE AN INTEREST IN BRITAIN'S INDUSTRIAL PAST. IT BRINGS TOGETHER PEOPLE WHO ARE RESEARCHING, RECORDING, PRESERVING AND PRESENTING THE GREAT VARIETY OF THIS COUNTRY'S INDUSTRIAL HERITAGE.",MR BARRY FRANK HOOD MSC MBA CENG ARSM,"9 KENNERTY PARK, PETERCULTER, AB14 0LE",http://www.industrial-archaeology.org.uk,01224 732558,1979-08-22,,2008-12-31,78272,123129,http://OpenlyLocal.com/charities/1-ASSOCIATION-FOR-INDUSTRIAL-ARCHAEOLOGY,2010-08-22T20:38:01+01:00,2010-08-30T08:05:56+01:00
INTERNATIONAL SOCIETY OF CHEMOTHERAPY FOR INFECTION AND CANCER,1029653,,"OBJECTIVES ARE TO ADVANCE THE EDUCATION AND SCIENCE OF CHEMOTHERAPY. INTERNATIONAL CONGRESSES PROMOTING THE DEVELOPMENT OF CHEMOTHERAPY ARE HELD REGULARLY. ISC ENCOURAGES, SUPPORTS AND SPONSORS THE FORMATION OF INTERNATIONAL WORKING GROUPS FOR SPECIAL RESEARCH PROJECTS, COMMISSIONS, TRAINING PROJECTS AND THE USE OF CHEMOTHERAPEUTICS IN THE FIELD OF ANTIMICROBIAL AND ANTINEOPLASTIC CHEMOTHERAPY.",FIONA MACKENZIE,"MEDICAL MICROBIOLOGY, ABERDEEN ROYAL INFIRMARY, CORNHILL ROAD, ABERDEEN, AB25 2ZN",http://www.ischemo.org,01224 552127,1993-12-03,,2008-12-31,207230,458259,http://OpenlyLocal.com/charities/2-INTERNATIONAL-SOCIETY-OF-CHEMOTHERAPY-FOR-INFECTION-AND-CANCER,2010-08-22T20:38:01+01:00,2010-08-30T08:05:58+01:00
BRITISH SOCIETY FOR MEDICAL MYCOLOGY,291852,4567,NO INFORMATION RECORDED,DR DONNA MACCALLUM,"ABERDEEN FUNGAL GROUP, SCHOOL OF MEDICAL SCIENCES, INSTITUTE OF MEDICAL SCIENCES, FORESTER HILL, ABERDEEN, AB25 2ZD",,01224 559536,1985-06-12,,2008-12-31,32781,47846,http://OpenlyLocal.com/charities/3-BRITISH-SOCIETY-FOR-MEDICAL-MYCOLOGY,2010-08-22T20:38:01+01:00,2010-08-30T08:05:59+01:00
}

**Comment by sebbacon** [comment]
1) Dates
At some point I think we should grasp the nettle re. dates and review the whole terminology we use. `sample_date`, as the field description in the schema implies, should be called something like `true_at`; we should always have `retrieved_at`; `should_be_renewed_at` (or `renewal_date`, but I'm thinking we should perhaps stick with rails conventions?) seems like a very good idea. If we think of `sample_date` as a synonym for `true_at`, then what does `last_updated_at` add?

2) GLEIs could be an "identifier register" perhaps?

**Comment by CountCulture** [comment]
1) Agree retrieved_at should be required. Prefer renewal_date to should_be_renewed_at. Not sure where the ref to last_updated_at comes from

2) I think identifier register feels like a stretch. If it's anything it's a register of legal entities, that issues identifiers. Similarly the US SAM system is a register of govt suppliers (that also ~ has CAGE identifiers)

**Comment by CountCulture** [comment]
merged in another PR

**Pull request closed without merging**
