### PR TITLE
Supplier relationships

### PR DESCRIPTION
**Pull request by bensymonds**

### CODE REVIEW

**Comment by CountCulture** [comment]
Looks sane. But if time allows would like some invalid examples. Most of the schema problems we've had have been down to invalid data not being marked as invalid

**Comment by bensymonds** [comment]
What kind of invalid examples would you put in? Obviously there are an infinite number of invalid examples we could come up with, but I don't really see any that would add value here. I agree we've had (have) problems with invalid data, but mostly that's been due to either suboptimal design (which wouldn't get caught by tests because they would just be reflecting the suboptimal design) or data issues which cannot currently be validated at the schema level...

rather than incorrect implementation, so wouldn't have been caught by tests.

**Comment by skenaja** [comment]
Some common invalid scenarios in https://github.com/openc/openc-schema/commit/0d01c5af8df9a11cf2b4044a801a8d81ff5a91d0 which could be replicated here.

Otherwise 👍

**Comment by bensymonds** [comment]
@dominicsayers Sorry I added another couple of commits. Very simple ones. 1f75b9f9d2575190565848942d6dcec41f1f74c5 and f5ae43c464110c62fb5cc62ec2bd0fb249561ebb.

**Comment by bensymonds** [comment]
Hmm yeah. Actually right now I'm confused why we bother running this against different versions of ruby - this is just a bunch of static json schemas so it doesn't matter which version of ruby (or indeed which _runtime_ - remember this gets used in (for example) python bots too!) it's used in. We just happen to use ruby to run the specs, but could just as easily use python or something. So actually probably we should just remove the multiple versions from the Travis build and just pick one to use for development.

But for now, I've removed the byebug commit :smile:

**Pull request merged**
