### PR TITLE
Both organisations and person can have identifiers

### PR DESCRIPTION
**Pull request by CountCulture**
So don't fail validation if they do!

### CODE REVIEW

**Comment by bensymonds** [comment]
Have we ever thought about adding `identifiers` in the top-level `entity` schema?

**Comment by CountCulture** [comment]
Yes, I have, but decided best to wait till we have a use case. Haven't
found one yet that wasn't a register of some sort

**Comment by bensymonds** [comment]
Not sure what you mean. I'm just thinking it seems logical to say that all entities, irrespective of `entity_type`, can have `identifiers` (and probably other things too, e.g. `name`). There's not really a use case to wait for.

Maybe for now we should just add them in the `entity_properties` like this though, to keep things consistent.

**Comment by bensymonds** [comment]
Discussed offline - we may want to move it into `entity` along with other common stuff, but leaving it for now. So this is good to go I think 👍

**Pull request merged**
