### PR TITLE
Require either company_number or name in company-for-nesting.json

### PR DESCRIPTION
**Pull request by jpmckinney**
The GB gazette scraper sometimes has numbers without names.

### CODE REVIEW

**Comment by jpmckinney** [comment]
@CountCulture @sebbacon GB is blocked by this.

**Comment by jpmckinney** [comment]
Note the changes that had to be made to the specs.

**Comment by CountCulture** [comment]
Can you give an example please

**Comment by jpmckinney** [comment]
https://www.thegazette.co.uk/notice/2471561

The GB scraper tries to use the RDFA, etc. tags to get company numbers and names, but otherwise just scans for company numbers using a regular expression.

**Comment by jpmckinney** [comment]
So you end up with:

```json
{
  ...
  "subjects": [{
    "entity_type": "company",
    "entity_properties": {
      "jurisdiction_code": "gb",
      "company_number": "06456689"
    }
  },
  ...
}
```

**Comment by CountCulture** [comment]
Makes sense. Go ahead

**Pull request merged**
